`timescale 1ns / 1ps

module sprite_overlay_enemy (
    input  wire [23:0] background_rgb,
    input  wire [8:0]  fb_x,
    input  wire [7:0]  fb_y,
    input  wire [8:0]  enemy_base_x,
    input  wire [7:0]  enemy_base_y,
    input  wire [31:0] enemy_alive_lo,
    input  wire [22:0] enemy_alive_hi,
    input  wire        enemy_enable,
    input  wire [8:0]  enemy_bullet_x,
    input  wire [7:0]  enemy_bullet_y,
    input  wire        enemy_bullet_enable,
    output wire [23:0] final_rgb
);

    // 5 rows (X direction) x 11 cols (Y direction) = 55 enemies
    // Cell stride: 13 logical px (~80% of the 180px screen width across 11 cols)
    // Visible sprite: 8x12 px, close to the aspect ratio of the original
    // Space Invaders characters. The 13x13 cell and collision layout are
    // unchanged, so this is a display-only size reduction.
    // Grid X span: 5*13=65px, Grid Y span: 11*13=143px (143/180 ~= 79%)
    // Stride 13 is not power-of-2, so row/col/cell position use compare
    // chains instead of bit-slicing (kept in sync with memfile.s, which has
    // no multiply/divide instruction and mirrors this with the same chain).

    wire in_grid_x = enemy_enable
                  && ({1'b0, fb_x} >= {1'b0, enemy_base_x})
                  && ({1'b0, fb_x} <  {1'b0, enemy_base_x} + 10'd65);

    wire in_grid_y = ({1'b0, fb_y} >= {1'b0, enemy_base_y})
                  && ({1'b0, fb_y} <  {1'b0, enemy_base_y} + 9'd143);

    wire [8:0] local_x = fb_x - enemy_base_x;
    wire [7:0] local_y = fb_y - enemy_base_y;

    wire [2:0] row = (local_x < 9'd13) ? 3'd0 :
                     (local_x < 9'd26) ? 3'd1 :
                     (local_x < 9'd39) ? 3'd2 :
                     (local_x < 9'd52) ? 3'd3 :
                                         3'd4;
    wire [8:0] row_start = (row == 3'd0) ? 9'd0  :
                           (row == 3'd1) ? 9'd13 :
                           (row == 3'd2) ? 9'd26 :
                           (row == 3'd3) ? 9'd39 :
                                           9'd52;

    wire [3:0] col = (local_y < 8'd13)  ? 4'd0  :
                     (local_y < 8'd26)  ? 4'd1  :
                     (local_y < 8'd39)  ? 4'd2  :
                     (local_y < 8'd52)  ? 4'd3  :
                     (local_y < 8'd65)  ? 4'd4  :
                     (local_y < 8'd78)  ? 4'd5  :
                     (local_y < 8'd91)  ? 4'd6  :
                     (local_y < 8'd104) ? 4'd7  :
                     (local_y < 8'd117) ? 4'd8  :
                     (local_y < 8'd130) ? 4'd9  :
                                          4'd10;
    wire [7:0] col_start = (col == 4'd0) ? 8'd0   :
                           (col == 4'd1) ? 8'd13  :
                           (col == 4'd2) ? 8'd26  :
                           (col == 4'd3) ? 8'd39  :
                           (col == 4'd4) ? 8'd52  :
                           (col == 4'd5) ? 8'd65  :
                           (col == 4'd6) ? 8'd78  :
                           (col == 4'd7) ? 8'd91  :
                           (col == 4'd8) ? 8'd104 :
                           (col == 4'd9) ? 8'd117 :
                                           8'd130;

    wire [8:0] cell_x = local_x - row_start; // 0..12 within the cell
    wire [7:0] cell_y = local_y - col_start; // 0..12 within the cell

    // Keep the 13px cell, but draw an 8px-tall x 12px-wide character.
    // cell_y is halved to select one of six master columns; each master
    // column therefore appears two logical pixels wide.
    wire in_cell = (cell_x < 9'd8) && (cell_y < 8'd12);
    wire [2:0] sprite_row = cell_x[2:0];
    wire [2:0] master_col = cell_y[3:1];

    // Match the classic formation: one small type at the top, two rows of
    // the middle type, and two rows of the lower type.
    wire [1:0] enemy_type = (row == 3'd0) ? 2'd0 :
                            (row <  3'd3) ? 2'd1 :
                                           2'd2;

    // One animation phase change per one-pixel formation movement. The
    // coordinate is already frame-latched in vpg.v, so every enemy switches
    // shape together without adding a CPU register or a ROM instruction.
    wire animation_phase = enemy_base_y[0];

    // Sprite ROM stores only the left half (three bits) of each six-column
    // master row. The right half is generated by mirroring master_col.
    // This reduces the shape table from 3 types * 2 frames * 8 * 6 bits to
    // 3 types * 2 frames * 8 * 3 bits.
    function [2:0] enemy_half_row;
        input [1:0] type_idx;
        input       frame_idx;
        input [2:0] row_idx;
        begin
            enemy_half_row = 3'b000;
            case (type_idx)
                // Upper "squid": narrow head and long animated feelers.
                2'd0: begin
                    case (row_idx)
                        3'd0: enemy_half_row = 3'b001; // 001100
                        3'd1: enemy_half_row = 3'b011; // 011110
                        3'd2: enemy_half_row = 3'b111; // 111111
                        3'd3: enemy_half_row = 3'b110; // 110011
                        3'd4: enemy_half_row = 3'b111; // 111111
                        3'd5: enemy_half_row = 3'b010; // 010010
                        3'd6: enemy_half_row = frame_idx ? 3'b010 : 3'b101;
                        3'd7: enemy_half_row = frame_idx ? 3'b101 : 3'b010;
                    endcase
                end

                // Middle "crab": wide arms and alternating legs.
                2'd1: begin
                    case (row_idx)
                        3'd0: enemy_half_row = 3'b010; // 010010
                        3'd1: enemy_half_row = 3'b101; // 101101
                        3'd2: enemy_half_row = 3'b111; // 111111
                        3'd3: enemy_half_row = 3'b110; // 110011
                        3'd4: enemy_half_row = 3'b111; // 111111
                        3'd5: enemy_half_row = 3'b011; // 011110
                        3'd6: enemy_half_row = frame_idx ? 3'b101 : 3'b010;
                        3'd7: enemy_half_row = frame_idx ? 3'b010 : 3'b101;
                    endcase
                end

                // Lower "octopus": solid body with two walking poses.
                default: begin
                    case (row_idx)
                        3'd0: enemy_half_row = 3'b011; // 011110
                        3'd1: enemy_half_row = 3'b111; // 111111
                        3'd2: enemy_half_row = 3'b110; // 110011
                        3'd3: enemy_half_row = 3'b111; // 111111
                        3'd4: enemy_half_row = 3'b011; // 011110
                        3'd5: enemy_half_row = 3'b101; // 101101
                        3'd6: enemy_half_row = frame_idx ? 3'b010 : 3'b100;
                        3'd7: enemy_half_row = frame_idx ? 3'b101 : 3'b010;
                    endcase
                end
            endcase
        end
    endfunction

    wire [2:0] half_row_bits =
        enemy_half_row(enemy_type, animation_phase, sprite_row);
    wire [1:0] mirrored_col = (master_col < 3'd3)
                            ? master_col[1:0]
                            : (3'd5 - master_col);
    wire in_sprite = in_cell && half_row_bits[2'd2 - mirrored_col];

    // enemy_idx = row * 11 + col (range 0..54)
    wire [5:0] row_base = (row == 3'd0) ? 6'd0  :
                          (row == 3'd1) ? 6'd11 :
                          (row == 3'd2) ? 6'd22 :
                          (row == 3'd3) ? 6'd33 :
                                          6'd44;
    wire [5:0] enemy_idx = row_base + {2'b0, col};

    // Alive bit lookup: lo word covers idx 0..31, hi word covers idx 32..54
    // enemy_idx[5]=1 means idx>=32; enemy_idx[4:0] gives the word-local bit position
    wire [31:0] enemy_alive_hi_ext = {9'd0, enemy_alive_hi};
    wire alive_lo = enemy_alive_lo[enemy_idx[4:0]];
    wire alive_hi = enemy_alive_hi_ext[enemy_idx[4:0]];
    wire alive    = enemy_idx[5] ? alive_hi : alive_lo;

    wire enemy_pixel = in_grid_x && in_grid_y && in_sprite && alive;

    // Column color: an 11-step rainbow sweep across the columns (Y axis),
    // so each column reads as a distinct color instead of uniform yellow.
    function [23:0] enemy_col_color;
        input [3:0] col_idx;
        begin
            case (col_idx)
                4'd0:  enemy_col_color = 24'hFF0044;
                4'd1:  enemy_col_color = 24'hFF6600;
                4'd2:  enemy_col_color = 24'hFFCC00;
                4'd3:  enemy_col_color = 24'hCCFF00;
                4'd4:  enemy_col_color = 24'h66FF00;
                4'd5:  enemy_col_color = 24'h00FF66;
                4'd6:  enemy_col_color = 24'h00FFCC;
                4'd7:  enemy_col_color = 24'h00CCFF;
                4'd8:  enemy_col_color = 24'h0066FF;
                4'd9:  enemy_col_color = 24'h6600FF;
                4'd10: enemy_col_color = 24'hCC00FF;
                default: enemy_col_color = 24'hFFFF00;
            endcase
        end
    endfunction

    wire [23:0] enemy_color = enemy_col_color(col);

    // Enemy bullet: same footprint as the player's bullet (sprite_overlay_bullet,
    // 8x2), but drawn here since memfile.s spawns/moves it as part of the
    // enemy-attack logic. Red so it reads as a threat, distinct from the
    // player's white bullet.
    localparam [9:0] EBULLET_WIDTH  = 10'd8;
    localparam [8:0] EBULLET_HEIGHT = 9'd2;

    wire enemy_bullet_pixel = enemy_bullet_enable
                            && (fb_x >= enemy_bullet_x)
                            && ({1'b0, fb_x} < ({1'b0, enemy_bullet_x} + EBULLET_WIDTH))
                            && (fb_y >= enemy_bullet_y)
                            && ({1'b0, fb_y} < ({1'b0, enemy_bullet_y} + EBULLET_HEIGHT));

    assign final_rgb = enemy_bullet_pixel ? 24'hFF0000 :
                        enemy_pixel       ? enemy_color :
                                            background_rgb;

endmodule
